// Generated by the protocol buffer compiler.  DO NOT EDIT!

@SuppressWarnings("hiding")
public interface ExampleProtos {

  public static final class Example extends
      com.google.protobuf.nano.MessageNano {

    public static final class Sub extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Sub[] _emptyArray;
      public static Sub[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Sub[0];
            }
          }
        }
        return _emptyArray;
      }

      // required int64 a = 100;
      public long a;

      // required double b = 101;
      public double b;

      public Sub() {
        clear();
      }

      public Sub clear() {
        a = 0L;
        b = 0D;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        output.writeInt64(100, this.a);
        output.writeDouble(101, this.b);
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(100, this.a);
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(101, this.b);
        return size;
      }

      @Override
      public Sub mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 800: {
              this.a = input.readInt64();
              break;
            }
            case 809: {
              this.b = input.readDouble();
              break;
            }
          }
        }
      }

      public static Sub parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Sub(), data);
      }

      public static Sub parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Sub().mergeFrom(input);
      }
    }

    private static volatile Example[] _emptyArray;
    public static Example[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Example[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string req = 1;
    public java.lang.String req;

    // optional int32 opt = 2;
    public int opt;

    // repeated .Example.Sub sub = 10;
    public ExampleProtos.Example.Sub[] sub;

    public Example() {
      clear();
    }

    public Example clear() {
      req = "";
      opt = 0;
      sub = ExampleProtos.Example.Sub.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.req);
      if (this.opt != 0) {
        output.writeInt32(2, this.opt);
      }
      if (this.sub != null && this.sub.length > 0) {
        for (int i = 0; i < this.sub.length; i++) {
          ExampleProtos.Example.Sub element = this.sub[i];
          if (element != null) {
            output.writeMessage(10, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.req);
      if (this.opt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.opt);
      }
      if (this.sub != null && this.sub.length > 0) {
        for (int i = 0; i < this.sub.length; i++) {
          ExampleProtos.Example.Sub element = this.sub[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(10, element);
          }
        }
      }
      return size;
    }

    @Override
    public Example mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.req = input.readString();
            break;
          }
          case 16: {
            this.opt = input.readInt32();
            break;
          }
          case 82: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 82);
            int i = this.sub == null ? 0 : this.sub.length;
            ExampleProtos.Example.Sub[] newArray =
                new ExampleProtos.Example.Sub[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.sub, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new ExampleProtos.Example.Sub();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new ExampleProtos.Example.Sub();
            input.readMessage(newArray[i]);
            this.sub = newArray;
            break;
          }
        }
      }
    }

    public static Example parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Example(), data);
    }

    public static Example parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Example().mergeFrom(input);
    }
  }
}
